spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/producttask1
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml/